---
- hosts: all
  become: true
  vars_files:
    - deploy/variables.yml

  tasks:
  
    # Pacotes
    
    - name: Aptitude
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Prerrequisitos
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Chave Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Repositório Docker
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Docker Community Edition
      apt: update_cache=yes name=docker-ce state=latest

    - name: Módulo Python
      pip:
        name: docker

    - name: Nginx
      apt: name=nginx update_cache=yes state=latest
      
    # Contêiner da aplicação

    - name: Diretório para build
      file:
        path: /root/bigapp
        state: directory
        owner: root
        group: root
        mode: '0755'
        
    - name: Arquivos do projeto
      copy:
        src: .
        dest: /root/bigapp
        owner: root
        group: root
        mode: '0644'
        
    - name: Executar o build
      docker_image:
        name: bigapp:v1.0
        build:
          pull: no
          path: /root/bigapp
        state: present
        source: build
        force_source: yes

    - name: Executar contêiner
      docker_container:
        name: bigapp
        image: bigapp:v1.0
        state: started
        recreate: yes
        published_ports:
          - "{{ app_port }}:{{ app_port }}"

    # Nginx

    - name: Configuração do Nginx
      template:
        src: "deploy/nginx.conf.j2"
        dest: "/etc/nginx/sites-available/{{ http_conf }}"

    - name: Habilita o site
      file:
        src: "/etc/nginx/sites-available/{{ http_conf }}"
        dest: "/etc/nginx/sites-enabled/{{ http_conf }}"
        state: link

    - name: Remove o site padrão do Nginx
      file:
        path: "/etc/nginx/sites-enabled/default"
        state: absent

    - name: "HTTP na porta {{ http_port }}"
      ufw:
        rule: allow
        port: "{{ http_port }}"
        proto: tcp
              
    - name: Recarrega Nginx
      service:
        name: nginx
        state: restarted

